[workspace]
channels = ["conda-forge"] # https://prefix.dev/conda-forge
name = "ctranslate2-rs-workspace"
platforms = [
    { platform = "linux-64", cuda = "12.9" },
]
version = "0.1.0"
preview = ["pixi-build"]

[package]
name = "ctranslate2-rs"
version = "0.10.1"
homepage = "https://github.com/jkawamoto/ctranslate2-rs"
repository = "https://github.com/jkawamoto/ctranslate2-rs"

[package.build]
backend = { name = "pixi-build-rust", version = "*" }

[package.build.config]
compilers = ["rust", "c", "cxx"]

[tasks]
clean = "cargo clean"
check = "cargo check"
build = "cargo build --release"
test = "cargo test --workspace"

[dependencies]
rust = "*"
rust-src = ">=1.98.1,<2"

cuda-version = "12.9.*"
cudnn = "8.*"
cuda-nvcc = "*"
libcublas-dev = "*"

compilers = ">=1.8.0"
cmake = ">=4.2.3,<5"
ninja = ">=1.13.2,<2"

sccache = ">=0.17.0,<0.18" # TODO we must configurate sccache ASAP!

[activation.env]
CFLAGS   = "$CFLAGS -pthread"
CXXFLAGS = "$CXXFLAGS -pthread"
CUDA_ARCH_LIST = "Auto"
CUDA_TOOLKIT_ROOT_DIR = "$CONDA_PREFIX/targets/x86_64-linux"
CUDA_PATH = "$CONDA_PREFIX/targets/x86_64-linux"

[environments]
default = []
# TODO this must be completed with all dependencies required by `ct2rs-platform`
platform = ["tensor-parallel"]

[feature.tensor-parallel.dependencies]
openmpi = "*"
nccl = "*"
