[workspace]
channels = ["conda-forge"] # https://prefix.dev/conda-forge
name = "ctranslate2-rs-workspace"
platforms = [
    { platform = "linux-64", cuda = "12.9" },
]
version = "0.1.0"
preview = ["pixi-build"]

[package]
name = "ctranslate2-rs"
version = "0.10.1"
homepage = "https://github.com/jkawamoto/ctranslate2-rs"
repository = "https://github.com/jkawamoto/ctranslate2-rs"

[package.build]
backend = { name = "pixi-build-rust", version = "*" }

[package.build.config]
compilers = ["rust", "c", "cxx"]

[tasks]
clean = "cargo clean"
check = "cargo check"
build = "cargo build --release"
test = "cargo test -- --all"

[dependencies]
rust = "*"

cuda-version = "12.9.*"
cudnn = "8.*"
cuda-nvcc = "*"
libcublas-dev = "*"
# cuda-cudart-dev = "*"
# libcurand-dev = "*"

# If WITH_TENSOR_PARALLEL
openmpi = "*"
nccl = "*"

compilers = ">=1.8.0"
cmake = ">=4.2.3,<5"
ninja = ">=1.13.2,<2"
# pkg-config = ">=0.29" <--- Why?

sccache = ">=0.17.0,<0.18" #TODO we must configurate sccache ASAP!

[activation.env]
CFLAGS   = "$CFLAGS -pthread"
CXXFLAGS = "$CXXFLAGS -pthread"
CUDA_ARCH_LIST = "Auto"
CUDA_TOOLKIT_ROOT_DIR = "$CONDA_PREFIX"
CUDA_PATH = "$CONDA_PREFIX"

# This is test only
WHISPER_MODEL = "$PIXI_PROJECT_ROOT/.models/faster-whisper-base"
